samples_se:


samples_pe:
    pop1:
        lib1:
            forward: data/reads/pop1_1.fastq.gz
            reverse: data/reads/pop1_2.fastq.gz
            adaptor: data/adapters/TruSeq3-PE-2.fa
            phred:   phred33
        # lib2:
        #     forward: data/reads/pop1_1.fastq.gz
        #     reverse: data/reads/pop1_2.fastq.gz
        #     adaptor: data/adapters/TruSeq3-PE-2.fa
        #     phred:   phred33
    pop2:
        lib1:
            forward: data/reads/pop2_1.fastq.gz
            reverse: data/reads/pop2_2.fastq.gz
            adaptor: data/adapters/TruSeq3-PE-2.fa
            phred:   phred33


pool_sizes:
    pop1: "500"
    pop2: "500"

reference:
    dna: data/genome/2R.chr.gz

chromosomes:
    2R

trimmomatic_params:
    "AVGQUAL:3 MINLEN:31 LEADING:19 TRAILING:19 MINLEN:31 SLIDINGWINDOW:4:5 LEADING:5 TRAILING:5 MINLEN:25 TOPHRED33"

bowtie2_params:
    "" #"--no-unal"

picard_markduplicates_params:
    memory: 1g

popoolation_params:
    find_indels:
        indel_window:       5
        min_count:          2
    subsample:
        minqual:            20
        method:             withoutreplace
        maxcoverage:        200
        targetcoverage:     10
    tajimad:
        mincount:           2
        mincoverage:        5
        maxcoverage:        200
        mincoveredfraction: 0.5
        stepsize:           1000
        windowsize:         1000
    tajimapi:
        mincount:           2
        mincoverage:        5
        maxcoverage:        200
        mincoveredfraction: 0.5
        stepsize:           1000
        windowsize:         1000
    theta:
        mincount:           2
        mincoverage:        5
        maxcoverage:        200
        mincoveredfraction: 0.5
        stepsize:           1000
        windowsize:         1000

popoolation2_params:
    mpileup2sync:
        min_qual:  20
    subsample_synchronized:
        target_coverage: 10
        max_coverage:    50
        method:          withoutreplace
    fst_sliding:
        window_size:          1
        step_size:            1
        min_covered_fraction: 1.0
        min_coverage:         4
        max_coverage:         120
        min_count:            3
